import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v16-appRouter";
import "@/../opentelemetry";
import { NavItem } from "@/components/layout/types";
import DashboardIcon from "@mui/icons-material/Dashboard";
import HomeIcon from "@mui/icons-material/Home";
import SettingsIcon from "@mui/icons-material/Settings";
import ResponsiveLayout from "@/components/layout/ResponsiveLayout";
import { LayoutProvider } from "@/context/LayoutContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems: NavItem[] = [
  { label: "Home", icon: <HomeIcon />, href: "/" },
  { label: "Dashboard", icon: <DashboardIcon />, href: "/dashboard" },
  { label: "Settings", icon: <SettingsIcon />, href: "/settings" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (typeof window !== "undefined") {
    const html = document.documentElement;
    if (
      html.hasAttribute("style") &&
      html.style.getPropertyValue("--vsc-domain")
    ) {
      html.removeAttribute("style");
    }
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppRouterCacheProvider>
          {" "}
          <LayoutProvider>
            <ResponsiveLayout navItems={navItems}>{children}</ResponsiveLayout>
          </LayoutProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
