version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssword123!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - db_net

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=YourStrong!Passw0rd
      - MYSQL_DATABASE=DB_NAME
      - MYSQL_USER=USERNAME
      - MYSQL_PASSWORD=PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db_net

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=USERNAME
      - POSTGRES_PASSWORD=PASSWORD
      - POSTGRES_DB=DB_NAME
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_net

  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle
    environment:
      - ORACLE_PASSWORD=PASSWORD
      - APP_USER=USERNAME
      - APP_USER_PASSWORD=PASSWORD
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - db_net

volumes:
  sql_data:
  mysql_data:
  postgres_data:
  oracle_data:

networks:
  db_net:
